# Generated by Django 4.0.5 on 2022-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0001_initial'),
        ('jwt_auth', '0005_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='shirts', to='shirts.shirt'),
        ),
    ]
