# Generated by Django 4.0.5 on 2022-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0005_alter_shirt_price'),
        ('jwt_auth', '0006_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='shirts', to='shirts.shirt'),
        ),
    ]
