# Generated by Django 4.0.5 on 2022-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
                ('year', models.PositiveBigIntegerField(default=None)),
                ('description', models.CharField(default=None, max_length=5000)),
                ('link', models.CharField(default=None, max_length=5000)),
                ('brand', models.CharField(default=None, max_length=50)),
                ('primary_image', models.CharField(default=None, max_length=1000)),
                ('image_two', models.CharField(default=None, max_length=1000)),
                ('image_three', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
