# Generated by Django 4.0.5 on 2022-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='league',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
