# Generated by Django 4.0.5 on 2022-06-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0002_shirt_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='price',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
